listener 1884
allow_anonymous true

log_type all

log_dest stdout

plugin /home/matteo/Desktop/thingsboard stack/waf/build/waf.so
plugin_opt_config_path /home/matteo/Desktop/thingsboard stack/waf/settings.yaml
plugin_opt_waf_rules_path /home/matteo/Desktop/thingsboard stack/waf/rules.yaml